name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write  # Required for creating releases

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.get_version.outputs.tag_name }}
      version: ${{ steps.get_version.outputs.version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version from tag
      id: get_version
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        VERSION=${TAG_NAME#v}
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Tag: $TAG_NAME, Version: $VERSION"

    - name: Extract changelog for this version
      run: |
        VERSION=${{ steps.get_version.outputs.version }}
        
        # Create a script to extract changelog
        cat << 'EOF' > extract_changelog.py
        import sys
        
        def extract_changelog(version):
            try:
                with open('CHANGELOG.md', 'r', encoding='utf-8') as f:
                    lines = f.readlines()
                
                # Find the version section
                start_index = -1
                for i, line in enumerate(lines):
                    if f'## [{version}]' in line:
                        start_index = i
                        break
                
                if start_index == -1:
                    return f"Release {version}\n\nChanges and improvements in this version."
                
                # Extract content until next ##
                content_lines = []
                for i in range(start_index + 1, len(lines)):
                    line = lines[i]
                    if line.startswith('## [') and f'[{version}]' not in line:
                        break
                    content_lines.append(line.rstrip())
                
                content = '\n'.join(content_lines).strip()
                
                if len(content.strip()) < 10:
                    return f"Release {version}\n\nChanges and improvements in this version."
                
                return content
                
            except Exception as e:
                return f"Release {version}\n\nError reading changelog: {str(e)}"
        
        if __name__ == "__main__":
            version = sys.argv[1]
            changelog = extract_changelog(version)
            print(changelog)
        EOF
        
        python extract_changelog.py "$VERSION" > release_notes.txt
        
        # Verify the file has content
        if [ ! -s release_notes.txt ]; then
          echo "Release $VERSION" > release_notes.txt
          echo "" >> release_notes.txt
          echo "Changes and improvements in this version." >> release_notes.txt
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v2
      id: create_release
      with:
        tag_name: ${{ steps.get_version.outputs.tag_name }}
        name: "CamLoader ${{ steps.get_version.outputs.tag_name }}"
        body_path: release_notes.txt
        draft: false
        prerelease: ${{ contains(steps.get_version.outputs.tag_name, '-') }}
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: false

  build-linux-x86_64:
    runs-on: ubuntu-latest
    needs: create-release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk python3-dev build-essential xvfb

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create x86_64 executable
      run: |
        # Set display for headless build
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        
        # Create PyInstaller spec for single executable
        cat << 'EOF' > camloader.spec
        # -*- mode: python ; coding: utf-8 -*-
        import sys
        import os
        from pathlib import Path
        
        src_path = Path.cwd() / 'src'
        sys.path.insert(0, str(src_path))
        
        datas = []
        if os.path.exists('data'):
            datas.append(('data', 'data'))
        
        a = Analysis(
            ['src/main.py'],
            pathex=[str(src_path)],
            binaries=[],
            datas=datas,
            hiddenimports=[
                'tkinter', 'tkinter.ttk', 'tkinter.filedialog', 'tkinter.messagebox',
                'PIL', 'PIL.Image', 'PIL.ImageTk', 'cv2', 'logging', 'json',
                'threading', 'subprocess', 'pathlib', 'datetime', 'platform'
            ],
            hookspath=[],
            hooksconfig={},
            runtime_hooks=[],
            excludes=[],
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=None,
            noarchive=False,
        )
        
        pyz = PYZ(a.pure, a.zipped_data, cipher=None)
        
        exe = EXE(
            pyz, a.scripts, a.binaries, a.zipfiles, a.datas, [],
            name='camloader-linux-x86_64',
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=False,
            upx_exclude=[],
            runtime_tmpdir=None,
            console=False,
            disable_windowed_traceback=False,
            argv_emulation=False,
            target_arch=None,
            codesign_identity=None,
            entitlements_file=None,
        )
        EOF
        
        # Build the executable
        pyinstaller camloader.spec --clean --noconfirm
        
        # Verify and test
        ls -la dist/
        chmod +x dist/camloader-linux-x86_64

    - name: Upload x86_64 executable
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.create-release.outputs.tag_name }}
        files: dist/camloader-linux-x86_64
        token: ${{ secrets.GITHUB_TOKEN }}

  build-source-package:
    runs-on: ubuntu-latest
    needs: create-release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel

    - name: Build source packages
      run: |
        python -m build --sdist --wheel
        ls -la dist/

    - name: Upload source packages
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ needs.create-release.outputs.tag_name }}
        files: |
          dist/*.tar.gz
          dist/*.whl
        token: ${{ secrets.GITHUB_TOKEN }}